// <auto-generated />
using System;
using Mde.Project.Mobile.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mde.Project.Mobile.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241010193630_remove-const")]
    partial class removeconst
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CargoProduct", b =>
                {
                    b.Property<Guid>("CargosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CargosId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CargoProduct");

                    b.HasData(
                        new
                        {
                            CargosId = new Guid("00000000-0000-0000-0000-000000000031"),
                            ProductsId = new Guid("00000000-0000-0000-0000-000000000021")
                        },
                        new
                        {
                            CargosId = new Guid("00000000-0000-0000-0000-000000000031"),
                            ProductsId = new Guid("00000000-0000-0000-0000-000000000022")
                        },
                        new
                        {
                            CargosId = new Guid("00000000-0000-0000-0000-000000000032"),
                            ProductsId = new Guid("00000000-0000-0000-0000-000000000022")
                        },
                        new
                        {
                            CargosId = new Guid("00000000-0000-0000-0000-000000000032"),
                            ProductsId = new Guid("00000000-0000-0000-0000-000000000023")
                        });
                });

            modelBuilder.Entity("Mde.Project.Mobile.WebAPI.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccessLevelType")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-100000000000",
                            AccessFailedCount = 0,
                            AccessLevelType = 2,
                            ConcurrencyStamp = "4b277cc7-bcb0-4d91-8aab-08dc4b606f7a",
                            Email = "Admin@fedex.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@FEDEX.COM",
                            NormalizedUserName = "ADMIN@FEDEX.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJvrxaY2rjUZxaDw4oEV2odZ1HEvAtKDhFLjmjTHdUICqD6qm4n+5xgTVwwnNIFFCQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "BABUNAPLANINAVHODCHETERI",
                            TwoFactorEnabled = false,
                            UserName = "Admin@fedex.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-200000000000",
                            AccessFailedCount = 0,
                            AccessLevelType = 0,
                            ConcurrencyStamp = "1YET1ANOTHER1UNIQUE1STRING1",
                            Email = "tom@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Tom",
                            LastName = "Calme",
                            LockoutEnabled = false,
                            NormalizedEmail = "TOM@GMAIL.COM",
                            NormalizedUserName = "TOM@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHUygX8lEsRXCq36P3zRH+zZGq9ljEHRgLbOvKma/21Cfqxq4QrDrNUXhGRu34jbtw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1DIFFERENT1UNIQUE1STRING1",
                            TwoFactorEnabled = false,
                            UserName = "tom@gmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-300000000000",
                            AccessFailedCount = 0,
                            AccessLevelType = 0,
                            ConcurrencyStamp = "2YET2ANOTHER2UNIQUE2STRING2",
                            Email = "sarah@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Sarah",
                            LastName = "Vrout",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAH@GMAIL.COM",
                            NormalizedUserName = "SARAH@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEcARinKMkI3ddUUWGzlGM1uGxxyCHz4UX5ykireuciFTC51iM4BTgxzjbzSDg6T9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2DIFFERENT2UNIQUE2STRING2",
                            TwoFactorEnabled = false,
                            UserName = "sarah@gmail.com"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-400000000000",
                            AccessFailedCount = 0,
                            AccessLevelType = 1,
                            ConcurrencyStamp = "3YET3ANOTHER3UNIQUE3STRING3",
                            Email = "milka@speedy.gr",
                            EmailConfirmed = true,
                            FirstName = "Milka",
                            LastName = "Stanis",
                            LockoutEnabled = false,
                            NormalizedEmail = "MILKA@SPEEDY.GR",
                            NormalizedUserName = "MILKA@SPEEDY.GR",
                            PasswordHash = "AQAAAAIAAYagAAAAEOuGF2SJ8wQvi/f9PGPc1PzuZZD4VWsBTBoNbBjLskq79YtuLCWt2TVTCf6ixNMjCw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3DIFFERENT3UNIQUE3STRING3",
                            TwoFactorEnabled = false,
                            UserName = "milka@speedy.gr"
                        });
                });

            modelBuilder.Entity("Mde.Project.Mobile.WebAPI.Entities.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalWeight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cargos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            Destination = "Milan",
                            TotalWeight = 1500.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            Destination = "London",
                            TotalWeight = 2900.0
                        });
                });

            modelBuilder.Entity("Mde.Project.Mobile.WebAPI.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Name = "Sportswear"
                        });
                });

            modelBuilder.Entity("Mde.Project.Mobile.WebAPI.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDangerous")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            IsDangerous = false,
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000012"),
                            IsDangerous = false,
                            Name = "Toaster"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000012"),
                            IsDangerous = false,
                            Name = "Sneakers"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000012"),
                            IsDangerous = false,
                            Name = "Training"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000060",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000061",
                            Name = "Driver",
                            NormalizedName = "DRIVER"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000063",
                            Name = "Consignee",
                            NormalizedName = "CONSIGNEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "00000000-0000-0000-0000-100000000000",
                            RoleId = "00000000-0000-0000-0000-000000000060"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-200000000000",
                            RoleId = "00000000-0000-0000-0000-000000000061"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-300000000000",
                            RoleId = "00000000-0000-0000-0000-000000000061"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-400000000000",
                            RoleId = "00000000-0000-0000-0000-000000000063"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CargoProduct", b =>
                {
                    b.HasOne("Mde.Project.Mobile.WebAPI.Entities.Cargo", null)
                        .WithMany()
                        .HasForeignKey("CargosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mde.Project.Mobile.WebAPI.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mde.Project.Mobile.WebAPI.Entities.Product", b =>
                {
                    b.HasOne("Mde.Project.Mobile.WebAPI.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Mde.Project.Mobile.WebAPI.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Mde.Project.Mobile.WebAPI.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mde.Project.Mobile.WebAPI.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Mde.Project.Mobile.WebAPI.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
